MINI_PLATFORM_VERSION = 12.1

MINI_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)

MINI_BUILDTYPE ?= UNOFFICIAL

MINI_VERSION_SUFFIX := $(MINI_BUILD_DATE)-$(MINI_BUILDTYPE)$(MINI_EXTRAVERSION)

# Internal version
MINI_VERSION := $(MINI_PLATFORM_VERSION)-$(MINI_VERSION_SUFFIX)

# Display version
MINI_DISPLAY_VERSION := $(MINI_PLATFORM_VERSION)-$(MINI_VERSION_SUFFIX)
